# Generated by Django 5.1.2 on 2025-08-27 07:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SpokenText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_content', models.TextField(help_text='The text has converted to speech')),
                ('voice_name', models.CharField(blank=True, help_text='name of the voice to use', max_length=50, null=True)),
                ('rate', models.FloatField(default=1.0, help_text='speed of the voice')),
                ('pitch', models.FloatField(default=1.0, help_text='pitch of the voice')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='The date and time the text was spoken')),
            ],
            options={
                'verbose_name': 'spoken text',
                'verbose_name_plural': 'spoken texts',
                'ordering': ['-created_at'],
            },
        ),
    ]
