# Generated by Django 5.1.2 on 2025-08-27 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nav', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='spokentext',
            options={},
        ),
        migrations.RemoveField(
            model_name='spokentext',
            name='text_content',
        ),
        migrations.RemoveField(
            model_name='spokentext',
            name='voice_name',
        ),
        migrations.AddField(
            model_name='spokentext',
            name='text',
            field=models.TextField(default='Default text'),
        ),
        migrations.AddField(
            model_name='spokentext',
            name='voice',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='spokentext',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='spokentext',
            name='pitch',
            field=models.FloatField(default=1.0),
        ),
        migrations.AlterField(
            model_name='spokentext',
            name='rate',
            field=models.FloatField(default=1.0),
        ),
    ]
