# Generated by Django 5.1.2 on 2025-08-28 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nav', '0002_alter_spokentext_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='spokentext',
            name='language',
            field=models.CharField(default='en', max_length=200),
        ),
        migrations.AddField(
            model_name='spokentext',
            name='translateed_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
